spring:
   datasource:
      url: jdbc:h2:~/data;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
      driverClassName: org.h2.Driver
      username: sa
      password: password
      jpa:
         database-platform: org.hibernate.dialect.H2Dialect
   h2:
      console:
         enabled: true
         path: /h2/
   jpa:
      hibernate:
         ddl-auto: update  
      properties:
         hibernate:
            search:
               default:
                  directory_provider: filesystem
                  indexBase: /home/nico/data/search-index

          
