//created on: Apr 20, 2020
package com.arit.adserve.rules.ebay

import com.arit.adserve.providers.ebay.EBayFindRequest;
import com.arit.adserve.providers.ebay.RequestState;
 

rule "Initial state for retrieving items"
dialect "mvel"
    when    
        $request: EBayFindRequest(state ==  RequestState.INITIAL)
    then
        $request.state = RequestState.RETRIEVE_ITEMS;
        $request.pageNumber = 1;        
        System.out.println($request);
end

rule "Need to retrieve items"
dialect "mvel"
    when    
        $request: EBayFindRequest(pageNumber * itemsPerPage  < maxRequiredItems && totalPages >= pageNumber + 1 
        && state ==  RequestState.RETRIEVE_ITEMS )
    then
        $request.pageNumber = $request.pageNumber + 1;        
        System.out.println($request);
end

rule "Need to update items"
dialect "mvel"
    when    
        $request: EBayFindRequest(pageNumber * itemsPerPage  >= maxRequiredItems && itemsUpdatedToday < itemsTotal)
    then
        $request.state = RequestState.UPDATE_ITEMS;
        $request.pageNumber = 1;        
        System.out.println($request);
end

rule "Reset to initial state for retrieving items"
dialect "mvel"
    when    
        $request: EBayFindRequest(state ==  RequestState.INITIAL)
    then
        $request.state = RequestState.RETRIEVE_ITEMS;
        $request.pageNumber = 1;        
        System.out.println($request);
end


